// <auto-generated />
using System;
using Blazor.DoctorsOffice.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Blazor.DoctorsOffice.Migrations
{
    [DbContext(typeof(DatabaseContext))]
    [Migration("20210307162053_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "6.0.0-preview.1.21102.2")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Blazor.DoctorsOffice.Database.Models.Diagnosis", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("DiseaseId")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("DiseaseId");

                    b.ToTable("Diagnoses");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DiseaseId = 1,
                            Title = "rash hands"
                        },
                        new
                        {
                            Id = 2,
                            DiseaseId = 2,
                            Title = "breathlessness"
                        },
                        new
                        {
                            Id = 3,
                            DiseaseId = 3,
                            Title = "rhinitis"
                        });
                });

            modelBuilder.Entity("Blazor.DoctorsOffice.Database.Models.Disease", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Diseases");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Allergy"
                        },
                        new
                        {
                            Id = 2,
                            Name = "cardiac cycle"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Cold"
                        });
                });

            modelBuilder.Entity("Blazor.DoctorsOffice.Database.Models.Patient", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("Birth")
                        .HasColumnType("Date");

                    b.Property<string>("FirstName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("SSN")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Patients");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Birth = new DateTime(1995, 5, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Klara",
                            LastName = "Schmidt",
                            SSN = 1234
                        },
                        new
                        {
                            Id = 2,
                            Birth = new DateTime(2001, 3, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Hans",
                            LastName = "Haubner",
                            SSN = 4567
                        },
                        new
                        {
                            Id = 3,
                            Birth = new DateTime(1990, 6, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Ilse",
                            LastName = "Puck",
                            SSN = 7896
                        });
                });

            modelBuilder.Entity("Blazor.DoctorsOffice.Database.Models.PatientDiagnosis", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("DiagnosisId")
                        .HasColumnType("int");

                    b.Property<int>("PatientId")
                        .HasColumnType("int");

                    b.Property<DateTime>("Visit")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("DiagnosisId");

                    b.HasIndex("PatientId");

                    b.ToTable("PatientDiagnoses");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DiagnosisId = 1,
                            PatientId = 1,
                            Visit = new DateTime(2020, 11, 19, 9, 3, 40, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 2,
                            DiagnosisId = 2,
                            PatientId = 2,
                            Visit = new DateTime(2020, 1, 28, 8, 3, 10, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 3,
                            DiagnosisId = 2,
                            PatientId = 3,
                            Visit = new DateTime(2019, 8, 14, 15, 3, 21, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 4,
                            DiagnosisId = 3,
                            PatientId = 2,
                            Visit = new DateTime(2021, 1, 17, 11, 15, 26, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 5,
                            DiagnosisId = 3,
                            PatientId = 1,
                            Visit = new DateTime(2020, 12, 12, 20, 3, 50, 0, DateTimeKind.Unspecified)
                        });
                });

            modelBuilder.Entity("Blazor.DoctorsOffice.Database.Models.Diagnosis", b =>
                {
                    b.HasOne("Blazor.DoctorsOffice.Database.Models.Disease", "Disease")
                        .WithMany()
                        .HasForeignKey("DiseaseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Disease");
                });

            modelBuilder.Entity("Blazor.DoctorsOffice.Database.Models.PatientDiagnosis", b =>
                {
                    b.HasOne("Blazor.DoctorsOffice.Database.Models.Diagnosis", "Diagnosis")
                        .WithMany()
                        .HasForeignKey("DiagnosisId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Blazor.DoctorsOffice.Database.Models.Patient", "Patient")
                        .WithMany()
                        .HasForeignKey("PatientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Diagnosis");

                    b.Navigation("Patient");
                });
#pragma warning restore 612, 618
        }
    }
}
