// <auto-generated />
using System;
using Blazor.MovieManagement.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Blazor.MovieManagement.Migrations
{
    [DbContext(typeof(DatabaseContext))]
    [Migration("20210308105531_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "6.0.0-preview.1.21102.2")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("ActorMovie", b =>
                {
                    b.Property<int>("ActorsId")
                        .HasColumnType("int");

                    b.Property<int>("MoviesId")
                        .HasColumnType("int");

                    b.HasKey("ActorsId", "MoviesId");

                    b.HasIndex("MoviesId");

                    b.ToTable("ActorMovie");
                });

            modelBuilder.Entity("Blazor.MovieManagement.Database.Models.Actor", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("CountryOfOrigin")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Actors");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CountryOfOrigin = "USA",
                            FirstName = "Leonardo",
                            LastName = "DiCaprio"
                        },
                        new
                        {
                            Id = 2,
                            CountryOfOrigin = "USA",
                            FirstName = "Kyle",
                            LastName = "Chandler"
                        },
                        new
                        {
                            Id = 3,
                            CountryOfOrigin = "USA",
                            FirstName = "Sandra ",
                            LastName = "Bullock"
                        },
                        new
                        {
                            Id = 4,
                            CountryOfOrigin = "USA",
                            FirstName = "Steve ",
                            LastName = "Carell"
                        });
                });

            modelBuilder.Entity("Blazor.MovieManagement.Database.Models.Movie", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("ProductionCompanyId")
                        .HasColumnType("int");

                    b.Property<DateTime>("ReleaseDate")
                        .HasColumnType("Date");

                    b.Property<string>("Title")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("ProductionCompanyId");

                    b.ToTable("Movies");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ProductionCompanyId = 1,
                            ReleaseDate = new DateTime(2021, 3, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Godzilla vs. Kong"
                        },
                        new
                        {
                            Id = 2,
                            ProductionCompanyId = 2,
                            ReleaseDate = new DateTime(2001, 2, 11, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Disney's American Legends"
                        },
                        new
                        {
                            Id = 3,
                            ProductionCompanyId = 3,
                            ReleaseDate = new DateTime(2015, 6, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Minions"
                        },
                        new
                        {
                            Id = 4,
                            ProductionCompanyId = 4,
                            ReleaseDate = new DateTime(2007, 7, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Transformers"
                        },
                        new
                        {
                            Id = 5,
                            ProductionCompanyId = 4,
                            ReleaseDate = new DateTime(1998, 1, 9, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Titanic"
                        });
                });

            modelBuilder.Entity("Blazor.MovieManagement.Database.Models.MovieActor", b =>
                {
                    b.Property<int>("ActorId")
                        .HasColumnType("int");

                    b.Property<int>("MovieId")
                        .HasColumnType("int");

                    b.HasKey("ActorId", "MovieId");

                    b.HasIndex("MovieId");

                    b.ToTable("MovieActors");

                    b.HasData(
                        new
                        {
                            ActorId = 2,
                            MovieId = 1
                        },
                        new
                        {
                            ActorId = 3,
                            MovieId = 3
                        },
                        new
                        {
                            ActorId = 4,
                            MovieId = 3
                        },
                        new
                        {
                            ActorId = 1,
                            MovieId = 5
                        });
                });

            modelBuilder.Entity("Blazor.MovieManagement.Database.Models.ProductionCompany", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("ProductionCompanies");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Warner Bros"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Walt Disney Studios"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Universal Pictures"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Paramount Pictures"
                        });
                });

            modelBuilder.Entity("ActorMovie", b =>
                {
                    b.HasOne("Blazor.MovieManagement.Database.Models.Actor", null)
                        .WithMany()
                        .HasForeignKey("ActorsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Blazor.MovieManagement.Database.Models.Movie", null)
                        .WithMany()
                        .HasForeignKey("MoviesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Blazor.MovieManagement.Database.Models.Movie", b =>
                {
                    b.HasOne("Blazor.MovieManagement.Database.Models.ProductionCompany", "ProductionCompany")
                        .WithMany()
                        .HasForeignKey("ProductionCompanyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ProductionCompany");
                });

            modelBuilder.Entity("Blazor.MovieManagement.Database.Models.MovieActor", b =>
                {
                    b.HasOne("Blazor.MovieManagement.Database.Models.Actor", "Actor")
                        .WithMany()
                        .HasForeignKey("ActorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Blazor.MovieManagement.Database.Models.Movie", "Movie")
                        .WithMany()
                        .HasForeignKey("MovieId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Actor");

                    b.Navigation("Movie");
                });
#pragma warning restore 612, 618
        }
    }
}
